// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Secret struct {
	ID                string
	EncryptedText     string
	IsClientEncrypted bool
	PasswordHash      sql.NullString
	NotifyEmail       sql.NullString
	FilePath          sql.NullString
	ExpiresAt         time.Time
	CreatedAt         time.Time
}
