// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cleanExpiredSecrets = `-- name: CleanExpiredSecrets :exec
DELETE FROM secrets 
WHERE expires_at < NOW()
`

func (q *Queries) CleanExpiredSecrets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredSecrets)
	return err
}

const createSecret = `-- name: CreateSecret :exec
INSERT INTO secrets (
    id, encrypted_text, is_client_encrypted, password_hash, notify_email, file_path, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateSecretParams struct {
	ID                string
	EncryptedText     string
	IsClientEncrypted bool
	PasswordHash      sql.NullString
	NotifyEmail       sql.NullString
	FilePath          sql.NullString
	ExpiresAt         time.Time
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) error {
	_, err := q.db.ExecContext(ctx, createSecret,
		arg.ID,
		arg.EncryptedText,
		arg.IsClientEncrypted,
		arg.PasswordHash,
		arg.NotifyEmail,
		arg.FilePath,
		arg.ExpiresAt,
	)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE id = $1
`

// Удаляем записку после успешного прочтения.
func (q *Queries) DeleteSecret(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, id)
	return err
}

const getExpiredSecrets = `-- name: GetExpiredSecrets :many
SELECT id, file_path FROM secrets 
WHERE expires_at < NOW()
`

type GetExpiredSecretsRow struct {
	ID       string
	FilePath sql.NullString
}

func (q *Queries) GetExpiredSecrets(ctx context.Context) ([]GetExpiredSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredSecretsRow
	for rows.Next() {
		var i GetExpiredSecretsRow
		if err := rows.Scan(&i.ID, &i.FilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSecretForRead = `-- name: GetSecretForRead :one
SELECT id, encrypted_text, is_client_encrypted, password_hash, notify_email, file_path, expires_at, created_at FROM secrets 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSecretForRead(ctx context.Context, id string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecretForRead, id)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.EncryptedText,
		&i.IsClientEncrypted,
		&i.PasswordHash,
		&i.NotifyEmail,
		&i.FilePath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSecretMeta = `-- name: GetSecretMeta :one
SELECT 
    id, 
    (password_hash IS NOT NULL)::boolean AS has_password, 
    is_client_encrypted
FROM secrets 
WHERE id = $1 LIMIT 1
`

type GetSecretMetaRow struct {
	ID                string
	HasPassword       bool
	IsClientEncrypted bool
}

func (q *Queries) GetSecretMeta(ctx context.Context, id string) (GetSecretMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getSecretMeta, id)
	var i GetSecretMetaRow
	err := row.Scan(&i.ID, &i.HasPassword, &i.IsClientEncrypted)
	return i, err
}
